### ISSUE TITLE
Use vim-plug instead of vim-pathogen

### ISSUE THREAD

**Issue by pickfire** [livibetter/dotfiles#3]
Hi, take a look at this [vim-plug](https://github.com/junegunn/vim-plug) and [this article](http://junegunn.kr/2014/07/vim-plugins-and-startup-time/) as the performance is almost the same and it support on-demand loading.

**Comment by livibetter** [comment]
@pickfire Thanks for the suggestion, but I won't make the switch. First, I am too lazy to switch and learn a new plugin system; second, the article specifically focusing the startup time, which isn't my concern.

I actually only have two plugins to be loaded by Pathogen, and as a matter of a fact, I run Vim in server mode, so the startup time -- if I understand correctly -- really doesn't matter to me. I only launch Vim a few times a month.

I only have Pathogen because I need a simple way to try out plugins. Now come to think about it, I haven't tried any plugins for some time, I might get rid of Pathogen.

Anyway, thanks, again.

**Comment by pickfire** [comment]
What about using `zsh`, it has a faster and better completion (although I didn't benchmark it), do you think you can use c in `zsh`'s prompt?

**Comment by livibetter** [comment]
@pickfire I'd believe Zsh is a better shell in terms of functionality, though I never used it. Completion isn't really a big factor to me, but I'd love to have float numbers in Bash.

I actually almost started to learn Zsh months ago, but didn't do it. Laziness got to me again, I suppose.

I don't know if you can extend Zsh, but skimming through its [toc][], there are modules, so that could be a possibility.

[toc]: http://zsh.sourceforge.net/Doc/Release/zsh_toc.html

**Comment by pickfire** [comment]
Look at https://github.com/sorin-ionescu/prezto which is a good framework for zsh. For configuration, look at my [simple dotfiles](https://github.com/pickfire/dotfiles/).
